services:
  # Servicio de backend (API Node.js)
  backend:
    build: ./backend
    ports:
      - "3050:3050"
    networks:
      - fullstack-network

  # Servicio de frontend (React/Vite servido con http-server)
  frontend:
    build: ./frontend # Usamos el Dockerfile corregido del frontend
    ports:
      - "3000:3000" # El puerto expuesto en el contenedor
    networks:
      - fullstack-network
    depends_on:
      - backend

networks:
  fullstack-network:
    driver: bridge
