services:

  backend:
    build: ./backend
    ports:
      - "3050:3050"
    networks:
      - fullstack-network
    restart: always
    
  frontend:
    build: ./frontend 
    ports:
      - "3000:3000" 
    networks:
      - fullstack-network
    depends_on:
      - backend
    restart: always
    
networks:
  fullstack-network:
    driver: bridge
